### ISSUE TITLE
D6 - 2. Implemented requirements

### ISSUE THREAD

**Issue by jadynlaila** [jadynlaila/Study_Group_Platform#132]
List in this section the requirements and associated pull request that you implemented for this release, following the example below---include the description of the requirement, a link to the issue,  a link to the pull request(s) that implement the requirement, who implemented the requirement, who approved it, and a print screen that depicts the implemented feature (if applicable). Order the requirements by the name of the student who implemented them. Everyone in the group is expected to have code contributions documented by means of pull requests. Every pull request should be reviewed and approved before the merge. 

At this point, we expect that you implement/prototype the features you specified in your MVP (c.f. D.2 Requirements). Pivots and changes are allowed as soon as you justify them.

See the example:

Requirement: As a Student, I want to add a homework assignment so that I can organize my ToDo list.Issue: <link to your GitHub issue>Pull request: https://github.com/user/project/pull/426Links to an external site.Implemented by: Martin FowlerApproved by: Ada LovelacePrint screen: A print screen that depicts the implemented feature (if applicable)
--

Example of Requirement Description
Requirement: As a Student, I want to add a homework assignment so that I can organize my ToDo list.

Issue: <link to your GitHub issue>

Pull request: [https://github.com/user/project/pull/426Links to an external site.](https://github.com/user/project/pull/426)

Implemented by: Martin Fowler

Approved by: Ada Lovelace

Print screen: A print screen that depicts the implemented feature (if applicable)

Remember that all code contributions should be submitted via pull requests and the reviewer should review and approve each pull request. 

Grading criteria (20 points): This section will be evaluated in terms of correctness, completeness, thoroughness, consistency, coherence, adequate use of language, and amount of work put into the implementation. Students can receive different grades depending on their involvement. It is expected that all members contribute with non-trivial implementation. All pull requests should be approved and integrated by the scrum master. You should follow an adequate workflow (description of the requirement on the issue tracker, submission of the implemented requirement as a pull request, and review of the pull request by another developer).

**Comment by NotYourAlejandro** [comment]
Fixed in #187
