### ISSUE TITLE
D6 - 3.1 Unit tests

### ISSUE THREAD

**Issue by jadynlaila** [jadynlaila/Study_Group_Platform#133]
A unit test is an automated test that aims to verify the behavior of a component isolated from the rest of the system. For this deliverable, show an example of a unit test that uses mock objects to isolate the class from the rest of the system. 

1. Test framework you used to develop your tests (e.g., JUnit, unittest, pytest, etc.)
2. Link to your GitHub folder where your automated unit tests are located
3. An example of a test case that makes use of mock objects. Include in your answer a GitHub link to the class being tested and to the test
4. A print screen showing the result of the unit test execution

Grading criteria (2 points): adequate choice of a test framework, coverage of the tests, quality of the tests, adequate use of Mock objects, and a print screen showing successful test execution.

**Comment by NotYourAlejandro** [comment]
Fixed in #185
