### ISSUE TITLE
D6 - 3.2 Acceptance Tests

### ISSUE THREAD

**Issue by jadynlaila** [jadynlaila/Study_Group_Platform#134]
An acceptance test is a test that verifies the correct implementation of a feature from the user interface perspective. An acceptance test is a black box test (the system is tested without knowledge about its internal implementation). Provide the following information:

1. Test framework you used to develop your tests (e.g., Selenium, Katalon Studio, Espresso2, Cucumber, etc.)
2. Link to your GitHub folder where your automated acceptance tests are located
3. An example of an acceptance test. Include a GitHub link to the test and an explanation about the tested feature in your answer.
4. A print screen/video showing the acceptance test execution
5. 
Grading criteria (2 points): adequate choice of a test framework, coverage of the tests, quality of the tests, adequate example of an acceptance test, print screen/video showing successful test execution.

**Comment by NotYourAlejandro** [comment]
Fixed in #185
