### ISSUE TITLE
Populate the "studentController" controller file

### ISSUE THREAD

**Issue by NotYourAlejandro** [jadynlaila/Study_Group_Platform#63]
## Requirements
- [ ] Define required functions
    - [ ] Populate the created functions

## Some Notes
- try to keep in line with UML Class Diagram since the frontend peeps will be calling these functions.

**Comment by jadynlaila** [comment]
Functions included: 
get, set, update, and delete student
get, add, and remove group for group list
get, set, update, and delete profile picture

**Comment by jadynlaila** [comment]
Priority for D4: create student, get student, add group, remove group
