### ISSUE TITLE
Main UI - GroupChat Module

### ISSUE THREAD

**Issue by vsv7nau** [jadynlaila/Study_Group_Platform#91]
Component on the right side, consists of enrolled group chats and groupchat search bar
REFER TO FIGMA PAGE FOR DETAILS

**Comment by JLealos** [comment]
The Group Chat Module is complete, see my latest push for review. It provides example groups and searches through the groups using a search bar. It also allows for a text to pop out using the text region component, separating the different groupchats.

**Comment by daira27** [comment]
This issue was completed
