### ISSUE TITLE
Main UI - Text Region

### ISSUE THREAD

**Issue by vsv7nau** [jadynlaila/Study_Group_Platform#92]
This part takes up majority of the page and consists of the typing are aswell as sent texts.
REFER TO FIGMA PAGE FOR DETAILS

**Comment by JLealos** [comment]
The text region component is function and is available for review with my recent push. You can text and see your displayed chats inside of the different group chats. However, without backend collaboration the chats cannot be stored and gone back to, and there is no way to test other user messages.
